### PR TITLE
Fix declare-function invocations for helm

### LINKED ISSUE #11: Startup problems when installed via the Guix package manager
I don't quite understand why, but using `with-eval-after-load` with `helm` is pretty screwy for me when installing this package via Guix.

This is what I did to fix it:

1. Add `"ext:"` to all the `declare-function`s (it seems that this is a must if using `declare-function` with external packages).
``` emacs-lisp
(declare-function helm-build-sync-source "ext:helm-source")
(declare-function helm-exit-and-execute-action "ext:helm")
(declare-function helm-marked-candidates "ext:helm")
(declare-function with-helm-alive-p "ext:helm")
(declare-function helm-make-actions "ext:helm-lib")
```

2. Presently, `declare-function` for `helm-build-sync-source` points to `ext:helm`, but it should point to `ext:helm-source`, so I made that change above.

3. Instead of using `with-eval-after-load`, simply use `require`.

The main problem with this is that we'll require `helm` as a dependency. An alternative is to split the `helm`-related parts into a separate package.

### PR DESCRIPTION
**Pull request by leungbk**
Closes #11.

### CODE REVIEW

**Comment by leungbk** [comment]
Friendly ping @alphapapa.

With macros, the trick seems to be to have a non-nil fourth arg to `declare-function`.

**Comment by alphapapa** [comment]
Why did you close this?

**Comment by leungbk** [comment]
> Why did you close this?

I realized that `declare-function` wouldn't work with macros even if the `FILEONLY` arg was non-nil, and I hadn't been using the package much, so I decided to close the PR rather than fix the PR.

...but now I've gone ahead and inserted the expanded forms of the `helm` macros, so I think everything should be good to go.

**Comment by alphapapa** [comment]
This should finally be obviated by moving Helm support to a separate package: https://github.com/alphapapa/org-recent-headings/commit/fda7a0ce356c6ecc88d93bc373fbd2f31106eb8a  Thanks.

**Pull request closed without merging**
