### PR TITLE
org-recent-headings-ivy: Add dispatch actions.

### PR DESCRIPTION
**Pull request by leungbk**
This might not be the most idiomatic way of doing this. I'd appreciate any feedback.

### CODE REVIEW

**Comment by leungbk** [comment]
I amended so that the `ivy` candidates now go something like `~/bob/todo.org:HEADING`, in order to disambiguate between same-name file/heading combos.

**Comment by leungbk** [comment]
I macro-ized the ivy-wrapper, so now we can simply run a `dolist` over the existing functions.

**Comment by alphapapa** [comment]
Hi Brian,

I apologize for neglecting this PR.  I looked at it soon after you sent it, and I meant to reply after I'd thought about it, but then I forgot to do that.

I appreciate the thoughtful way you've implemented this, but it feels a little heavy to me, defining a macro and `-ivy` copies of all those functions.  Could we just use lambdas in `ivy-set-actions`?  Maybe something like:

    (ivy-set-actions 'org-recent-headings-ivy
                     '(("n" (lambda (candidate)
                              (interactive) ; Not sure if `interactive' is necessary.
                              (org-recent-headings--show-entry-indirect (cdr candidate)))
                        "show in indirect buffer")))

I'm also not sure about the `make-tuple` function.  The `display` slot of each entry is meant to be what's displayed.  If you want to make that more customizable, that's not a bad idea, but it should be done in a way that works for all variants, not just the Ivy ones.

What do you think?

Thanks.

**Comment by leungbk** [comment]
Hey @alphapapa, thanks for your feedback. I've switched to use lambdas, and reverted to using the existing `display` property.

**Comment by alphapapa** [comment]
@leungbk  As noted in the other issues, Helm support has been moved to a separate package, and Ivy support was also removed from the main package: https://github.com/alphapapa/org-recent-headings/commit/fda7a0ce356c6ecc88d93bc373fbd2f31106eb8a  If you'd like to propose an Ivy-specific package, I'm open to that idea.

**Pull request closed without merging**
